
paths:
  /api/products:
    get:
      summary: Obtenemos todos los productos
      tags:
      - products
      responses:
        "200":
          description: Productos cargados correctamente
        "500":
          description: Error al recuperar productos
    
    post:
      summary: Crear un nuevo producto
      tags:
        - products
      requestBody:
        description: Datos del nuevo producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productModel'
        required: true
      responses:
        "200":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productModel'
        "500":
          description: Error al crear el producto

  /api/products/{id}:  
    
    put:
      summary: Actualizar un producto por ID
      tags:
        - products
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
            format: objectId
      requestBody:
        description: Datos actualizados del producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productModel'
        required: true
      responses:
        "200":
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productModel'
        "404":
          description: Producto no encontrado
        "500":
          description: Error al actualizar el producto

    delete:
      summary: Eliminar un producto por ID
      tags:
        - products
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
            format: objectId
      responses:
        "204":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error al eliminar el producto

components:
  schemas:
    productModel: 
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por mongo 
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto 
        thumbnail:
          type: String
          description: Fotografia del producto
        code:
          type: number
          description: Codigo identificador para el producto
        stock:
          type: Number
          description: Cantidad de productos en stock
        status:
          type: Boolean
          description: Por defecto es "true"
        category:
          type: String
          description: Categoria del producto
      example:
        _id: Objectid('669829ee9d28680d8977b2ab')
        title: samsung M12
        description: Pantalla 5.2, 5g, Color Azul
        price: 150.000
        thumbnail: link de la imgen
        code: 1235
        stock: 25
        status: true
        category: Smartphones
